name: Run Scout-action
description: Run scout-action
author: devops_cf

# Define your inputs here.
inputs:
  target:
    description: Folder to scan for Cargo.toml
    required: true
    default: "."

  scout_args:
    description: Scout args
    required: false
    default: "-v"

  markdown_output:
    description: Generate markdown output
    required: false
    default: "false"

# Define your outputs here.
# -> At the moment the output will be: ${{ github.workspace }}/report.md
#outputs:
#  mdreport:
#    description: markdown report

#run docker
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.target }}
  env:
    INPUT_TARGET: ${{ inputs.target }}
    INPUT_MARKDOWN_OUTPUT: ${{ inputs.markdown_output }}
    INPUT_SCOUT_ARGS: ${{ inputs.scout_args }}
