name: Run Scout-action
description: Run scout-action
author: Coinfabrik

# Define your inputs here.
inputs:
  target:
    description: Folder to scan for Cargo.toml
    required: true
    default: "."
  scout_args:
    description: Scout args
    required: false
    default: "-v --output-format md-gh --output-path /github/workspace/report.md --cicd /github/workspace"
  scout_extra_args:
    description: Scout extra args
    required: false
    default: ""
#run docker
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.target }}
  env:
    INPUT_TARGET: ${{ inputs.target }}
    INPUT_SCOUT_ARGS: "${{ inputs.scout_args }} ${{ inputs.scout_extra_args }} "
