name: Run Scout-action
description: Run scout-action
author: devops_cf

# Define your inputs here.
inputs:
  target:
    description: Folder to scan
    required: true
    default: target

# Define your outputs here.
outputs:
  time:
    description: Time execution

#run docker
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.target }}
  env:
    INPUT_TARGET: ${{ inputs.target}}
