name: Build Docker Image

on:
  push:
    branches:
      - soroban

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: soroban   # Checkout del branch 'soroban'

    - name: Build Docker image
      run: docker build -t scout-qa .

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Espera a que el trabajo 'build' se complete antes de comenzar

    steps:
    - name: Insufficiently-random-values
      run: |
        docker image ls
        docker run -e TARGET='insufficiently-random-values_vulnerable-example' --name scout-qa scout-qa
