name: Build Docker Image

on:
  push:
    branches:
      - soroban

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: soroban   # Checkout del branch 'soroban'

    - name: Build Docker image
      run: docker build -t scout-qa .
